project:
  type: website

website:
  title: "NIU College of Business"
  #page-navigation: true
  #site-url: https://vineelnekkanti.github.io/omis-dashboard
  #repo-url: https://github.com/vineelnekkanti/omis-dashboard
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




